(function(){
const DB=window.ASSET_LIFELOG_DB;
const {dstr,todayIso}=window.AssetVisionCommon;
const {parseAmountInput,runCommonOcr,extractOcrValues}=window.AssetVisionOcr;
const {persistSavedRows}=window.AssetVisionStorage;
let importImageDataUrl=null;
let importOcrText="";
let importOcrResult=null;
let pendingImportOverwrite=null;
let importStateVersion=0;
let activeImportProfileKey="sbiIdeco";
let hooks={rows:null,refreshAfterSave:null,openModal:null,closeModal:null,closeModalIfOpen:null};
const importProfiles={
  sbiIdeco:{title:"SBI iDeCo取込",channelId:"ideco_gold",assetGroup:"iDeCo",sourceName:"SBI iDeCo",sourceType:"screenshot_ocr",pasteMessage:"SBI iDeCoのスクショを貼り付け",ocrProfile:"sbi_ideco"},
  saisonNisa:{title:"セゾンNISA取込",channelId:"saison_nisa",assetGroup:"セゾンNISA",sourceName:"セゾン投信",sourceType:"screenshot_ocr",pasteMessage:"セゾンNISAのスクショを貼り付け",ocrProfile:"saison_nisa"}
};
function activeImportProfile(){return importProfiles[activeImportProfileKey]||importProfiles.sbiIdeco}
function setImportMessage(msg,cls=""){const el=document.getElementById("sbiMessage");if(el){el.className=`message ${cls}`;el.innerHTML=msg?msg.replaceAll("\n","<br>"):""}}
function showToast(msg,cls="good"){let el=document.getElementById("toast");if(!el){el=document.createElement("div");el.id="toast";el.className="toast";document.body.appendChild(el)}el.textContent=msg;el.className=`toast show ${cls}`;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>{el.classList.remove("show")},3000)}
function updateImportSaveButtonState(){const btn=document.getElementById("sbiSaveBtn");if(!btn)return;const dateValue=(document.getElementById("sbiDate")?.value||"").trim();const amount=parseAmountInput(document.getElementById("sbiAmount")?.value);btn.disabled=!(dateValue&&amount!=null)}
function setOcrState(msg){const el=document.getElementById("sbiOcrState");if(el)el.textContent=msg||""}
function setImportImageSelected(selected){const drop=document.getElementById("sbiDropZone"),wrap=document.getElementById("sbiPreviewWrap"),actions=document.getElementById("sbiImageActions");if(drop)drop.hidden=!!selected;if(wrap)wrap.hidden=!selected;if(actions)actions.hidden=!selected}
function clearImportImage(){importImageDataUrl=null;const img=document.getElementById("sbiPreview");if(img)img.removeAttribute("src");setImportImageSelected(false)}
function resetImportReadState({resetDate=true}={}){importOcrText="";importOcrResult=null;pendingImportOverwrite=null;hooks.closeModalIfOpen();const date=document.getElementById("sbiDate"),amountInput=document.getElementById("sbiAmount"),saveBtn=document.getElementById("sbiSaveBtn");if(resetDate&&date)date.value=todayIso();clearImportAmountValue(amountInput);if(saveBtn)saveBtn.textContent="保存";setImportMessage("");setOcrState("");updateImportSaveButtonState()}
function clearImportAmountValue(amountInput=document.getElementById("sbiAmount")){
  if(!amountInput)return;
  amountInput.value="";
  amountInput.defaultValue="";
}
function resetImportForm(){
  importStateVersion++;
  clearImportImage();
  resetImportReadState();
  const input=document.getElementById("sbiImageInput");
  if(input)input.value="";
}
function updateImportProfileUi(){const p=activeImportProfile();document.querySelectorAll(".importProfileTab").forEach(btn=>btn.classList.toggle("active",btn.dataset.importProfile===activeImportProfileKey));const title=document.getElementById("importTitle");if(title)title.textContent=p.title;const paste=document.getElementById("importPasteMessage");if(paste)paste.textContent=p.pasteMessage;const label=document.getElementById("importAssetGroupLabel");if(label)label.textContent=`${p.assetGroup}（固定）`;const preview=document.getElementById("sbiPreview");if(preview)preview.alt=`${p.title}スクリーンショットプレビュー`;resetImportForm()}
function handleImportFile(file){if(!file||!file.type.startsWith("image/")){setImportMessage("画像ファイルを選択してください。","bad");return}const reader=new FileReader();reader.onload=()=>{importStateVersion++;resetImportReadState();importImageDataUrl=reader.result;document.getElementById("sbiPreview").src=importImageDataUrl;setImportImageSelected(true);runImportOcr()};reader.readAsDataURL(file)}
async function runImportOcr(){const p=activeImportProfile();const startedVersion=importStateVersion;const startedProfileKey=activeImportProfileKey;if(!importImageDataUrl){setImportMessage("画像を貼り付けるか選択してください。","bad");return}setOcrState("OCR実行中...");setImportMessage("");try{const text=await runCommonOcr(importImageDataUrl,{onProgress:m=>{if(startedVersion===importStateVersion&&startedProfileKey===activeImportProfileKey)setOcrState(`OCR実行中... ${Math.round((m.progress||0)*100)}%`)}});if(startedVersion!==importStateVersion||startedProfileKey!==activeImportProfileKey)return;importOcrText=text;const {amount,baseDate}=extractOcrValues(text,p);importOcrResult={amount,baseDate,profileKey:activeImportProfileKey};const messages=[];let messageClass="";if(baseDate){document.getElementById("sbiDate").value=baseDate}else{document.getElementById("sbiDate").value=todayIso();messages.push("基準日を認識できませんでした。\n今日の日付をセットしています。必要に応じて変更してください。");messageClass="bad"}if(amount){document.getElementById("sbiAmount").value=amount.toLocaleString("ja-JP")}else{messages.push("評価額を認識できませんでした。\n\n画像プレビューを見ながら手入力してください。");messageClass="bad"}setOcrState("");setImportMessage(messages.join("\n\n"),messageClass);updateImportSaveButtonState()}catch(e){if(startedVersion!==importStateVersion||startedProfileKey!==activeImportProfileKey)return;importOcrText="";importOcrResult=null;document.getElementById("sbiDate").value=todayIso();setOcrState("");setImportMessage("基準日を認識できませんでした。\n今日の日付をセットしています。必要に応じて変更してください。\n\n評価額を認識できませんでした。\n\n画像プレビューを見ながら手入力してください。","bad");updateImportSaveButtonState()}}
function buildImportRow(profile,date,amount){const rs=hooks.rows(profile.channelId);const pr=rs.filter(r=>r.date<date).at(-1)||rs.at(-1);const principal=profile.channelId==="ideco_gold"?(pr?.principal??null):null;const profit=principal==null?null:amount-principal;return{date,channelId:profile.channelId,asset_group:profile.assetGroup,asset:amount,amount,principal,profit,profitRate:principal?profit/principal:null,reportedDailyChange:null,source:"screenshot_ocr",source_name:profile.sourceName,source_type:profile.sourceType}}
function upsertDailyRow(row){const i=DB.accountDaily.findIndex(r=>r.date===row.date&&r.channelId===row.channelId);if(i>=0)DB.accountDaily[i]={...DB.accountDaily[i],...row};else DB.accountDaily.push(row);persistSavedRows()}
function completeImportSave(profile,date,mode){hooks.refreshAfterSave(profile.channelId);resetImportForm();showToast(`${dstr(date)} の${profile.assetGroup}データを${mode==="update"?"更新":"登録"}しました。`)}
function performImportSave({overwrite=false,triggerButton=null,date=null,amount=null,profileKey=null}={}){const profile=importProfiles[profileKey]||activeImportProfile();const saveDate=date||document.getElementById("sbiDate").value;const saveAmount=amount??parseAmountInput(document.getElementById("sbiAmount").value);if(!saveDate){setImportMessage("基準日を入力してください。","bad");return false}if(saveAmount==null){setImportMessage("評価額を数値として入力してください。","bad");updateImportSaveButtonState();return false}if(triggerButton){triggerButton.disabled=true;triggerButton.textContent=overwrite?"更新中...":"保存中..."}const saveBtn=document.getElementById("sbiSaveBtn");if(saveBtn)saveBtn.disabled=true;upsertDailyRow(buildImportRow(profile,saveDate,saveAmount));completeImportSave(profile,saveDate,overwrite?"update":"insert");return true}
function openImportOverwriteConfirm(profile,date,amount){pendingImportOverwrite={profileKey:activeImportProfileKey,date,amount};hooks.openModal(`同じ基準日の${profile.assetGroup}データが既に存在します。`,`<div class="confirmText">既存データを上書きしますか？</div><div class="actionRow"><button class="primaryBtn" id="sbiOverwriteBtn" type="button">上書き</button><button id="sbiOverwriteCancelBtn" type="button">キャンセル</button></div>`);const overwriteBtn=document.getElementById("sbiOverwriteBtn");const cancelBtn=document.getElementById("sbiOverwriteCancelBtn");if(overwriteBtn)overwriteBtn.addEventListener("click",()=>{const payload=pendingImportOverwrite;if(!payload)return;overwriteBtn.disabled=true;if(cancelBtn)cancelBtn.disabled=true;overwriteBtn.textContent="更新中...";hooks.closeModal();pendingImportOverwrite=null;performImportSave({overwrite:true,triggerButton:null,date:payload.date,amount:payload.amount,profileKey:payload.profileKey})},{once:true});if(cancelBtn)cancelBtn.addEventListener("click",()=>{pendingImportOverwrite=null;hooks.closeModal()},{once:true})}
function saveActiveImport(){const profile=activeImportProfile();const date=document.getElementById("sbiDate").value;const amount=parseAmountInput(document.getElementById("sbiAmount").value);if(!date){setImportMessage("基準日を入力してください。","bad");return}if(amount==null){setImportMessage("評価額を数値として入力してください。","bad");updateImportSaveButtonState();return}const exists=DB.accountDaily.some(r=>r.date===date&&r.channelId===profile.channelId);if(exists){openImportOverwriteConfirm(profile,date,amount);return}performImportSave({overwrite:false,triggerButton:document.getElementById("sbiSaveBtn"),date,amount})}
function setup(options={}){hooks={...hooks,...options};const date=document.getElementById("sbiDate");if(!date)return;const drop=document.getElementById("sbiDropZone"),input=document.getElementById("sbiImageInput"),amount=document.getElementById("sbiAmount");if(amount){amount.autocomplete="off";clearImportAmountValue(amount)}document.querySelectorAll(".importProfileTab").forEach(btn=>btn.addEventListener("click",()=>{const nextKey=btn.dataset.importProfile;if(!nextKey||nextKey===activeImportProfileKey)return;activeImportProfileKey=nextKey;updateImportProfileUi()}));document.getElementById("sbiSelectImageBtn").onclick=()=>input.click();document.getElementById("sbiChangeImageBtn").onclick=()=>input.click();input.onchange=e=>handleImportFile(e.target.files?.[0]);date.addEventListener("input",updateImportSaveButtonState);if(amount)amount.addEventListener("input",updateImportSaveButtonState);document.getElementById("sbiRerunOcrBtn").onclick=runImportOcr;document.getElementById("sbiSaveBtn").onclick=()=>saveActiveImport();drop.addEventListener("click",e=>{if(e.target.id!=="sbiSelectImageBtn")input.click()});drop.addEventListener("dragover",e=>{e.preventDefault();drop.classList.add("dragover")});drop.addEventListener("dragleave",()=>drop.classList.remove("dragover"));drop.addEventListener("drop",e=>{e.preventDefault();drop.classList.remove("dragover");handleImportFile(e.dataTransfer.files?.[0])});document.addEventListener("paste",e=>{const item=[...(e.clipboardData?.items||[])].find(x=>x.type.startsWith("image/"));if(item)handleImportFile(item.getAsFile())});updateImportProfileUi();window.addEventListener("beforeunload",clearImportImage)}
function closeModalIfOpen(){const backdrop=document.getElementById("modalBackdrop");if(backdrop&&backdrop.style.display!=="none")backdrop.style.display="none"}

window.AssetVisionImport={setup,clearImportImage,resetImportForm,runImportOcr,saveActiveImport};
})();
