const DB=window.ASSET_LIFELOG_DB;let selectedChannel="ideco_gold";let selectedRange="1Y";let importImageDataUrl=null;let importOcrText="";let importOcrResult=null;let pendingImportOverwrite=null;let activeImportProfileKey="sbiIdeco";
const importProfiles={
  sbiIdeco:{title:"SBI iDeCo取込",channelId:"ideco_gold",assetGroup:"iDeCo",sourceName:"SBI iDeCo",sourceType:"screenshot_ocr",pasteMessage:"SBI iDeCoのスクショを貼り付け",ocrProfile:"sbi_ideco"},
  saisonNisa:{title:"セゾンNISA取込",channelId:"saison_nisa",assetGroup:"セゾンNISA",sourceName:"セゾン投信",sourceType:"screenshot_ocr",pasteMessage:"セゾンNISAのスクショを貼り付け",ocrProfile:"saison_nisa"}
};
const STORAGE_KEY="assetVision.accountDaily.v1";
const {yen,pct,dstr,byDate,todayIso,parseAmountInput,normalizeOcrText,toIsoDate,numberCandidates}=window.AssetVisionCommon;
function loadSavedRows(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}}
function persistSavedRows(){const custom=DB.accountDaily.filter(r=>r.source_type==="screenshot_ocr"||r.source==="screenshot_ocr");localStorage.setItem(STORAGE_KEY,JSON.stringify(custom))}
function mergeSavedRows(){for(const r of loadSavedRows()){const i=DB.accountDaily.findIndex(x=>x.date===r.date&&x.channelId===r.channelId);if(i>=0)DB.accountDaily[i]={...DB.accountDaily[i],...r};else DB.accountDaily.push(r)}}
const channels=()=>DB.channels.filter(c=>c.active).sort((a,b)=>(a.displayOrder??0)-(b.displayOrder??0));const channel=id=>DB.channels.find(c=>c.id===id);
const rows=id=>DB.accountDaily.filter(r=>r.channelId===id&&r.asset!=null).sort(byDate);const purpose=id=>DB.purposeMaster.find(p=>p.id===id);const latest=id=>rows(id).at(-1);const prev=id=>rows(id).at(-2);const change=(a,b)=>(a==null||b==null)?null:a-b;
function mainPurposeLabel(c){const p=purpose(c.mainPurpose);return p?`${p.icon} ${p.label}`:"-"}function allPurposeLabels(c){return(c.purposes||[]).map(id=>{const p=purpose(id);return p?`${p.icon} ${p.label}`:id}).join(" / ")}
function lastMemoForChannel(id){return DB.channelMemos.filter(m=>m.channelId===id).sort(byDate).at(-1)}function latestMarketMemo(){return DB.marketMemos.slice().sort(byDate).at(-1)}
function totalLatest(){let total=0,has=false;for(const c of channels()){const r=latest(c.id);if(r){total+=r.asset;has=true}}return has?total:null}
function totalPrev(){let total=0,has=false;for(const c of channels()){const r=prev(c.id);if(r){total+=r.asset;has=true}}return has?total:null}
function monthStartTotal(){const all=channels().map(c=>latest(c.id)).filter(Boolean);if(!all.length)return null;const lastDate=all.map(r=>r.date).sort().at(-1);const ym=lastDate.slice(0,7);let total=0,has=false;for(const c of channels()){const rs=rows(c.id).filter(r=>r.date.slice(0,7)===ym);if(rs.length){total+=rs[0].asset;has=true}}return has?total:null}
function maxDrawdown(rs){let peak=-Infinity,peakDate=null,maxDd=0,maxDdDate=null;for(const r of rs){if(r.asset>peak){peak=r.asset;peakDate=r.date}const dd=r.asset-peak;if(dd<maxDd){maxDd=dd;maxDdDate=r.date}}return{value:maxDd,peakDate,date:maxDdDate}}
function renderSummary(){const t=totalLatest(),p=totalPrev(),ms=monthStartTotal();const diff=change(t,p),mdiff=change(t,ms);document.getElementById("summary").innerHTML=`
<div class="card"><h2>総資産</h2><div class="big">${yen(t)}</div><div class="small">登録済み資産グループ合計</div></div>
<div class="card"><h2>前回比</h2><div class="big ${diff>=0?"good":"bad"}">${diff==null?"-":yen(diff)}</div><div class="small">登録済みデータ同士の比較</div></div>
<div class="card"><h2>月初比</h2><div class="big ${mdiff>=0?"good":"bad"}">${mdiff==null?"-":yen(mdiff)}</div><div class="small">最新月の初回データ比</div></div>
<div class="card"><h2>総評</h2><button class="commentBtn" onclick="openMarketMemo()">💬</button><div class="small">資産間のつながりを見る</div></div>`}
function renderChannelTable(){const total=totalLatest();const trs=channels().map(c=>{const r=latest(c.id),pr=prev(c.id),memo=lastMemoForChannel(c.id);const diff=r&&pr?r.asset-pr.asset:null;const share=total&&r?r.asset/total:null;return`<tr><td><button class="nameBtn" onclick="openChannelDetail('${c.id}')">${c.name}</button></td><td><span class="purpose">${mainPurposeLabel(c)}</span></td><td>${r?yen(r.asset):"未登録"}</td><td class="${diff>=0?"good":"bad"}">${diff==null?"-":yen(diff)}</td><td>${r?yen(r.profit):"-"}</td><td>${share==null?"-":(share*100).toFixed(1)+"%"}</td><td><button class="commentBtn ${memo?"":"empty"}" onclick="openChannelMemo('${c.id}')">${memo?"💬":"○"}</button></td></tr>`}).join("");document.getElementById("channelTable").innerHTML=`<table><thead><tr><th>資産グループ</th><th>目的</th><th>評価額</th><th>前回比</th><th>損益</th><th>比率</th><th>コメント</th></tr></thead><tbody>${trs}</tbody></table>`}
function setupControls(){document.getElementById("channelSelect").innerHTML=channels().map(c=>`<option value="${c.id}">${c.name}</option>`).join("");document.getElementById("channelSelect").value=selectedChannel;document.getElementById("channelSelect").onchange=e=>{selectedChannel=e.target.value;renderChart();renderDataTable()};document.querySelectorAll("[data-range]").forEach(btn=>{btn.classList.toggle("active",btn.dataset.range===selectedRange);btn.onclick=()=>{selectedRange=btn.dataset.range;setupControls();renderChart();renderDataTable()}})}
function daysForRange(){return {"1M":31,"3M":93,"6M":186,"1Y":366}[selectedRange]||null}
function rangeRows(rs){const days=daysForRange();if(!days)return rs;if(!rs.length)return rs;const last=new Date(rs.at(-1).date);const min=new Date(last);min.setDate(min.getDate()-days);return rs.filter(r=>new Date(r.date)>=min)}
function niceStep(range){const steps=[10000,20000,50000,100000,250000,500000,1000000,2500000,5000000,10000000];const target=range/4;return steps.find(s=>s>=target)||steps.at(-1)}
function niceYScale(vals){let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min-=50000;max+=50000}const step=niceStep(max-min);const y0=Math.floor(min/step)*step;const y1=Math.ceil(max/step)*step;let ticks=[];for(let v=y0;v<=y1+step/2;v+=step)ticks.push(v);return{y0,y1,step,ticks}}
function formatX(dateStr){const [y,m,d]=dateStr.split("-");if(selectedRange==="all")return `${y}/${Number(m)}`;return `${Number(m)}/${Number(d)}`}
function rangeLabel(){return {"1M":"1か月","3M":"3か月","6M":"半年","1Y":"1年",all:"全期間"}[selectedRange]||selectedRange}
function moneyDisplayMode(){return DB.settings?.moneyDisplayMode||DB.settings?.amountUnit||localStorage.getItem("moneyDisplayMode")||"man"}
function summaryValue(n,{signed=false}={}){if(n==null||Number.isNaN(n))return "-";const sign=signed?(n>0?"+":n<0?"-":"±"):"";const abs=Math.abs(n);if(moneyDisplayMode()==="yen")return `${sign}${yen(abs)}`;return `${sign}${Math.round(abs/10000).toLocaleString("ja-JP")}万円`}
function statusItem(label,value,cls="",valueCls=""){return `<span class="statusItem"><span class="statusLabel">${label}</span><b class="${cls} ${valueCls}">${value}</b></span>`}
function renderChartStatus(rs){const el=document.getElementById("chartStatus");if(!el)return;if(rs.length<2){el.innerHTML="";return}const first=rs[0],last=rs.at(-1),diff=last.asset-first.asset;const diffClass=diff>0?"good":diff<0?"bad":"";el.innerHTML=[statusItem("期間",`${dstr(first.date)} ～ ${dstr(last.date)}`),statusItem("現在値",summaryValue(last.asset),"","currentValue"),statusItem("期間増減",summaryValue(diff,{signed:true}),diffClass)].join("")}
function renderChart(){const c=channel(selectedChannel);const rs=rangeRows(rows(selectedChannel));const el=document.getElementById("chart");if(rs.length<2){el.innerHTML=`<div class="small">グラフ表示には2件以上のデータが必要です。</div>`;renderChartStatus(rs);return}const w=el.clientWidth||850,h=el.clientHeight||320,m={l:64,r:18,t:18,b:42};const vals=rs.map(r=>r.asset),sc=niceYScale(vals),y0=sc.y0,y1=sc.y1;const x=i=>m.l+(i/(rs.length-1))*(w-m.l-m.r);const y=v=>h-m.b-((v-y0)/(y1-y0))*(h-m.t-m.b);const path=rs.map((r,i)=>`${i===0?"M":"L"}${x(i).toFixed(1)},${y(r.asset).toFixed(1)}`).join(" ");const xCount=Math.min(7,rs.length);const xIdx=Array.from({length:xCount},(_,i)=>Math.round((rs.length-1)*i/(xCount-1)));const grid=sc.ticks.map(v=>`<line class="gridline" x1="${m.l}" x2="${w-m.r}" y1="${y(v)}" y2="${y(v)}"/>`).join("");const ylabs=sc.ticks.map(v=>`<text x="${m.l-8}" y="${y(v)+4}" text-anchor="end">${(v/10000).toLocaleString("ja-JP")}万</text>`).join("");const xlabs=xIdx.map(i=>`<text x="${x(i)}" y="${h-14}" text-anchor="middle">${formatX(rs[i].date)}</text>`).join("");el.innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><g class="axis">${grid}${ylabs}${xlabs}<line x1="${m.l}" x2="${w-m.r}" y1="${h-m.b}" y2="${h-m.b}"/><line x1="${m.l}" x2="${m.l}" y1="${m.t}" y2="${h-m.b}"/></g><path class="path" d="${path}" stroke="${c.color}"/><circle cx="${x(rs.length-1)}" cy="${y(rs.at(-1).asset)}" r="4" fill="${c.color}"/></svg>`;renderChartStatus(rs)}
function renderDataTable(){const rsFull=rows(selectedChannel);const rs=rangeRows(rsFull).slice().reverse().slice(0,50);document.getElementById("dataTable").innerHTML=`<table><thead><tr><th>日付</th><th>評価額</th><th>元本/拠出金</th><th>損益</th><th>損益率</th><th>前回比</th></tr></thead><tbody>${rs.map(r=>{const idx=rsFull.findIndex(x=>x.date===r.date);const pr=idx>0?rsFull[idx-1]:null;const diff=pr?r.asset-pr.asset:null;return`<tr><td>${dstr(r.date)}</td><td>${yen(r.asset)}</td><td>${yen(r.principal)}</td><td>${yen(r.profit)}</td><td>${pct(r.profitRate)}</td><td class="${diff>=0?"good":"bad"}">${diff==null?"-":yen(diff)}</td></tr>`}).join("")}</tbody></table>`}
function extractCommonBaseDate(text){const normalized=normalizeOcrText(text).replace(/\s+/g," ");let m=normalized.match(/(20\d{2})\s*[\/\-.年]\s*(\d{1,2})\s*[\/\-.月]\s*(\d{1,2})\s*(?:日)?\s*現在/);if(m)return toIsoDate(m[1],m[2],m[3]);m=normalized.match(/現在\s*(20\d{2})\s*[\/\-.年]\s*(\d{1,2})\s*[\/\-.月]\s*(\d{1,2})/);if(m)return toIsoDate(m[1],m[2],m[3]);m=normalized.match(/基準日[^0-9]*(20\d{2})\s*[\/\-.年]\s*(\d{1,2})\s*[\/\-.月]\s*(\d{1,2})/);if(m)return toIsoDate(m[1],m[2],m[3]);return null}
function extractAmountNearKeywords(text,keywords){const normalized=normalizeOcrText(text);const lines=normalized.split(/\n+/).map(x=>x.trim()).filter(Boolean);for(let i=0;i<lines.length;i++){if(keywords.test(lines[i])){const area=lines.slice(i,Math.min(i+4,lines.length)).join(" ");const found=numberCandidates(area).sort((a,b)=>b-a)[0];if(found)return found}}return null}
function extractSbiAmount(text){return extractAmountNearKeywords(text,/評価額|資産評価額|時価評価額/)||numberCandidates(text).sort((a,b)=>b-a)[0]||null}
function extractSaisonAmount(text){return extractAmountNearKeywords(text,/評価額|評価金額|資産評価額|資産合計|合計評価額|時価評価額|お預り資産|NISA/)||numberCandidates(text).sort((a,b)=>b-a)[0]||null}
const ocrExtractors={sbi_ideco:{baseDate:extractCommonBaseDate,amount:extractSbiAmount},saison_nisa:{baseDate:extractCommonBaseDate,amount:extractSaisonAmount}};
function activeImportProfile(){return importProfiles[activeImportProfileKey]||importProfiles.sbiIdeco}
function setImportMessage(msg,cls=""){const el=document.getElementById("sbiMessage");if(el){el.className=`message ${cls}`;el.innerHTML=msg?msg.replaceAll("\n","<br>"):""}}
function showToast(msg,cls="good"){let el=document.getElementById("toast");if(!el){el=document.createElement("div");el.id="toast";el.className="toast";document.body.appendChild(el)}el.textContent=msg;el.className=`toast show ${cls}`;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>{el.classList.remove("show")},3000)}
function updateImportSaveButtonState(){const btn=document.getElementById("sbiSaveBtn");if(!btn)return;const dateValue=(document.getElementById("sbiDate")?.value||"").trim();const amount=parseAmountInput(document.getElementById("sbiAmount")?.value);btn.disabled=!(dateValue&&amount!=null)}
function setOcrState(msg){const el=document.getElementById("sbiOcrState");if(el)el.textContent=msg||""}
function setImportImageSelected(selected){const drop=document.getElementById("sbiDropZone"),wrap=document.getElementById("sbiPreviewWrap"),actions=document.getElementById("sbiImageActions");if(drop)drop.hidden=!!selected;if(wrap)wrap.hidden=!selected;if(actions)actions.hidden=!selected}
function clearImportImage(){importImageDataUrl=null;importOcrText="";importOcrResult=null;const img=document.getElementById("sbiPreview");if(img)img.removeAttribute("src");setOcrState("");setImportImageSelected(false)}
function resetImportForm(){clearImportImage();pendingImportOverwrite=null;closeModalIfOpen();const date=document.getElementById("sbiDate"),amount=document.getElementById("sbiAmount"),input=document.getElementById("sbiImageInput"),saveBtn=document.getElementById("sbiSaveBtn");if(date)date.value=todayIso();if(amount)amount.value="";if(input)input.value="";if(saveBtn)saveBtn.textContent="保存";setImportMessage("");setOcrState("");updateImportSaveButtonState()}
function updateImportProfileUi(){const p=activeImportProfile();document.querySelectorAll(".importProfileTab").forEach(btn=>btn.classList.toggle("active",btn.dataset.importProfile===activeImportProfileKey));const title=document.getElementById("importTitle");if(title)title.textContent=p.title;const paste=document.getElementById("importPasteMessage");if(paste)paste.textContent=p.pasteMessage;const label=document.getElementById("importAssetGroupLabel");if(label)label.textContent=`${p.assetGroup}（固定）`;const preview=document.getElementById("sbiPreview");if(preview)preview.alt=`${p.title}スクリーンショットプレビュー`;resetImportForm()}
function handleImportFile(file){if(!file||!file.type.startsWith("image/")){setImportMessage("画像ファイルを選択してください。","bad");return}const reader=new FileReader();reader.onload=()=>{importImageDataUrl=reader.result;document.getElementById("sbiPreview").src=importImageDataUrl;setImportImageSelected(true);setImportMessage("");runImportOcr()};reader.readAsDataURL(file)}
async function runCommonOcr(imageDataUrl){if(!window.Tesseract)throw new Error("OCR engine is not loaded");const result=await Tesseract.recognize(imageDataUrl,"jpn+eng",{logger:m=>{if(m.status)setOcrState(`OCR実行中... ${Math.round((m.progress||0)*100)}%`)}});return result?.data?.text||""}
function extractOcrValues(text,profile){const ex=ocrExtractors[profile.ocrProfile]||ocrExtractors.sbi_ideco;return{baseDate:ex.baseDate(text),amount:ex.amount(text),rawText:text}}
async function runImportOcr(){const p=activeImportProfile();if(!importImageDataUrl){setImportMessage("画像を貼り付けるか選択してください。","bad");return}setOcrState("OCR実行中...");setImportMessage("");try{const text=await runCommonOcr(importImageDataUrl);importOcrText=text;const {amount,baseDate}=extractOcrValues(text,p);importOcrResult={amount,baseDate,profileKey:activeImportProfileKey};const messages=[];let messageClass="";if(baseDate){document.getElementById("sbiDate").value=baseDate}else{document.getElementById("sbiDate").value=todayIso();messages.push("基準日を認識できませんでした。\n今日の日付をセットしています。必要に応じて変更してください。");messageClass="bad"}if(amount){document.getElementById("sbiAmount").value=amount.toLocaleString("ja-JP")}else{messages.push("評価額を認識できませんでした。\n\n画像プレビューを見ながら手入力してください。");messageClass="bad"}setOcrState("");setImportMessage(messages.join("\n\n"),messageClass);updateImportSaveButtonState()}catch(e){importOcrText="";importOcrResult=null;document.getElementById("sbiDate").value=todayIso();setOcrState("");setImportMessage("基準日を認識できませんでした。\n今日の日付をセットしています。必要に応じて変更してください。\n\n評価額を認識できませんでした。\n\n画像プレビューを見ながら手入力してください。","bad");updateImportSaveButtonState()}}
function buildImportRow(profile,date,amount){const rs=rows(profile.channelId);const pr=rs.filter(r=>r.date<date).at(-1)||rs.at(-1);const principal=profile.channelId==="ideco_gold"?(pr?.principal??null):null;const profit=principal==null?null:amount-principal;return{date,channelId:profile.channelId,asset_group:profile.assetGroup,asset:amount,amount,principal,profit,profitRate:principal?profit/principal:null,reportedDailyChange:null,source:"screenshot_ocr",source_name:profile.sourceName,source_type:profile.sourceType}}
function upsertDailyRow(row){const i=DB.accountDaily.findIndex(r=>r.date===row.date&&r.channelId===row.channelId);if(i>=0)DB.accountDaily[i]={...DB.accountDaily[i],...row};else DB.accountDaily.push(row);persistSavedRows()}
function completeImportSave(profile,date,mode){renderSummary();renderChannelTable();selectedChannel=profile.channelId;setupControls();renderChart();renderDataTable();resetImportForm();showToast(`${dstr(date)} の${profile.assetGroup}データを${mode==="update"?"更新":"登録"}しました。`)}
function performImportSave({overwrite=false,triggerButton=null,date=null,amount=null,profileKey=null}={}){const profile=importProfiles[profileKey]||activeImportProfile();const saveDate=date||document.getElementById("sbiDate").value;const saveAmount=amount??parseAmountInput(document.getElementById("sbiAmount").value);if(!saveDate){setImportMessage("基準日を入力してください。","bad");return false}if(saveAmount==null){setImportMessage("評価額を数値として入力してください。","bad");updateImportSaveButtonState();return false}if(triggerButton){triggerButton.disabled=true;triggerButton.textContent=overwrite?"更新中...":"保存中..."}const saveBtn=document.getElementById("sbiSaveBtn");if(saveBtn)saveBtn.disabled=true;upsertDailyRow(buildImportRow(profile,saveDate,saveAmount));completeImportSave(profile,saveDate,overwrite?"update":"insert");return true}
function openImportOverwriteConfirm(profile,date,amount){pendingImportOverwrite={profileKey:activeImportProfileKey,date,amount};openModal(`同じ基準日の${profile.assetGroup}データが既に存在します。`,`<div class="confirmText">既存データを上書きしますか？</div><div class="actionRow"><button class="primaryBtn" id="sbiOverwriteBtn" type="button">上書き</button><button id="sbiOverwriteCancelBtn" type="button">キャンセル</button></div>`);const overwriteBtn=document.getElementById("sbiOverwriteBtn");const cancelBtn=document.getElementById("sbiOverwriteCancelBtn");if(overwriteBtn)overwriteBtn.addEventListener("click",()=>{const payload=pendingImportOverwrite;if(!payload)return;overwriteBtn.disabled=true;if(cancelBtn)cancelBtn.disabled=true;overwriteBtn.textContent="更新中...";closeModal();pendingImportOverwrite=null;performImportSave({overwrite:true,triggerButton:null,date:payload.date,amount:payload.amount,profileKey:payload.profileKey})},{once:true});if(cancelBtn)cancelBtn.addEventListener("click",()=>{pendingImportOverwrite=null;closeModal()},{once:true})}
function saveActiveImport(){const profile=activeImportProfile();const date=document.getElementById("sbiDate").value;const amount=parseAmountInput(document.getElementById("sbiAmount").value);if(!date){setImportMessage("基準日を入力してください。","bad");return}if(amount==null){setImportMessage("評価額を数値として入力してください。","bad");updateImportSaveButtonState();return}const exists=DB.accountDaily.some(r=>r.date===date&&r.channelId===profile.channelId);if(exists){openImportOverwriteConfirm(profile,date,amount);return}performImportSave({overwrite:false,triggerButton:document.getElementById("sbiSaveBtn"),date,amount})}
function setupImport(){const date=document.getElementById("sbiDate");if(!date)return;const drop=document.getElementById("sbiDropZone"),input=document.getElementById("sbiImageInput"),amount=document.getElementById("sbiAmount");document.querySelectorAll(".importProfileTab").forEach(btn=>btn.addEventListener("click",()=>{const nextKey=btn.dataset.importProfile;if(!nextKey||nextKey===activeImportProfileKey)return;activeImportProfileKey=nextKey;updateImportProfileUi()}));document.getElementById("sbiSelectImageBtn").onclick=()=>input.click();document.getElementById("sbiChangeImageBtn").onclick=()=>input.click();input.onchange=e=>handleImportFile(e.target.files?.[0]);date.addEventListener("input",updateImportSaveButtonState);if(amount)amount.addEventListener("input",updateImportSaveButtonState);document.getElementById("sbiRerunOcrBtn").onclick=runImportOcr;document.getElementById("sbiSaveBtn").onclick=()=>saveActiveImport();drop.addEventListener("click",e=>{if(e.target.id!=="sbiSelectImageBtn")input.click()});drop.addEventListener("dragover",e=>{e.preventDefault();drop.classList.add("dragover")});drop.addEventListener("dragleave",()=>drop.classList.remove("dragover"));drop.addEventListener("drop",e=>{e.preventDefault();drop.classList.remove("dragover");handleImportFile(e.dataTransfer.files?.[0])});document.addEventListener("paste",e=>{const item=[...(e.clipboardData?.items||[])].find(x=>x.type.startsWith("image/"));if(item)handleImportFile(item.getAsFile())});updateImportProfileUi();window.addEventListener("beforeunload",clearImportImage)}
function closeModalIfOpen(){const backdrop=document.getElementById("modalBackdrop");if(backdrop&&backdrop.style.display!=="none")backdrop.style.display="none"}
const setSbiMessage=setImportMessage,updateSbiSaveButtonState=updateImportSaveButtonState,resetSbiImportForm=resetImportForm,clearSbiImage=clearImportImage,runSbiOcr=runImportOcr,saveSbiIdeco=saveActiveImport,setupSbiImport=setupImport;
function openModal(title,body){document.getElementById("modalTitle").innerHTML=title;document.getElementById("modalBody").innerHTML=body;document.getElementById("modalBackdrop").style.display="flex"}function closeModal(){pendingImportOverwrite=null;document.getElementById("modalBackdrop").style.display="none"}
function stars(c){if(c==null)return"-";const n=Math.round(c*5);return"★★★★★".slice(0,n)+"☆☆☆☆☆".slice(0,5-n)}
function openMarketMemo(){const m=latestMarketMemo();if(!m){openModal("今日の総評",`<div class="small">総評コメントはありません。</div>`);return}openModal("今日の総評",`<h3>市況</h3><div>${m.summary}</div><h3>資産間のつながり</h3><div>${m.relation}</div><h3>今日の学び</h3><div>${m.learning}</div><div class="confidence">信頼度：${stars(m.confidence)} / tags: ${(m.tags||[]).join(", ")}</div>`)}
function openChannelMemo(id){const c=channel(id),m=lastMemoForChannel(id);if(!m){openModal(`${c.name} のコメント`,`<div class="small">コメントはまだありません。</div>`);return}openModal(`${c.name} のコメント`,`<h3>今日のコメント</h3><div>${m.comment}</div><h3>今日の学び</h3><div>${m.learning}</div><div class="confidence">信頼度：${stars(m.confidence)}</div>`)}
function openChannelDetail(id){const c=channel(id),rs=rows(id),r=rs.at(-1),pr=rs.at(-2),diff=r&&pr?r.asset-pr.asset:null;const high=rs.length?rs.reduce((a,b)=>b.asset>a.asset?b:a,rs[0]):null;const low=rs.length?rs.reduce((a,b)=>b.asset<a.asset?b:a,rs[0]):null;const dd=rs.length?maxDrawdown(rs):null;openModal(`${c.name} の詳細`,`<div class="detailGrid"><div class="detailItem"><b>目的</b>${allPurposeLabels(c)}</div><div class="detailItem"><b>最新資産</b>${r?yen(r.asset):"未登録"}</div><div class="detailItem"><b>前回比</b><span class="${diff>=0?"good":"bad"}">${diff==null?"-":yen(diff)}</span></div><div class="detailItem"><b>損益</b>${r?yen(r.profit):"-"} / ${r?pct(r.profitRate):"-"}</div><div class="detailItem"><b>最高値</b>${high?yen(high.asset):"-"}<br><span class="small">${high?dstr(high.date):""}</span></div><div class="detailItem"><b>最低値</b>${low?yen(low.asset):"-"}<br><span class="small">${low?dstr(low.date):""}</span></div></div><h3>運用方針</h3><div>${c.policy||"-"}</div><h3>メモ</h3><div>${c.note||"-"}</div><div class="confidence">最大ドローダウン：${dd?yen(dd.value):"-"} ${dd?`(${dstr(dd.peakDate)} → ${dstr(dd.date)})`:""}</div>`)}
function init(){mergeSavedRows();document.getElementById("appVer").textContent=`${DB.app.name} v${DB.app.version}`;renderSummary();renderChannelTable();setupControls();renderChart();renderDataTable();setupImport();document.getElementById("modalBackdrop").addEventListener("click",e=>{if(e.target.id==="modalBackdrop")closeModal()})}
init();
