const DB=window.ASSET_LIFELOG_DB;let selectedChannel="ideco_gold";let selectedRange="1Y";
const {yen,pct,dstr,byDate}=window.AssetVisionCommon;
const {loadSavedRows,persistSavedRows,mergeSavedRows}=window.AssetVisionStorage;
const {rangeRows}=window.AssetVisionChart;
const {openModal,closeModal,closeModalIfOpen}=window.AssetVisionModal;
const channels=()=>DB.channels.filter(c=>c.active).sort((a,b)=>(a.displayOrder??0)-(b.displayOrder??0));const channel=id=>DB.channels.find(c=>c.id===id);
const rows=id=>DB.accountDaily.filter(r=>r.channelId===id&&r.asset!=null).sort(byDate);const purpose=id=>DB.purposeMaster.find(p=>p.id===id);const latest=id=>rows(id).at(-1);const prev=id=>rows(id).at(-2);const change=(a,b)=>(a==null||b==null)?null:a-b;
function mainPurposeLabel(c){const p=purpose(c.mainPurpose);return p?`${p.icon} ${p.label}`:"-"}function allPurposeLabels(c){return(c.purposes||[]).map(id=>{const p=purpose(id);return p?`${p.icon} ${p.label}`:id}).join(" / ")}
function lastMemoForChannel(id){return DB.channelMemos.filter(m=>m.channelId===id).sort(byDate).at(-1)}function latestMarketMemo(){return DB.marketMemos.slice().sort(byDate).at(-1)}
function totalLatest(){let total=0,has=false;for(const c of channels()){const r=latest(c.id);if(r){total+=r.asset;has=true}}return has?total:null}
function totalPrev(){let total=0,has=false;for(const c of channels()){const r=prev(c.id);if(r){total+=r.asset;has=true}}return has?total:null}
function monthStartTotal(){const all=channels().map(c=>latest(c.id)).filter(Boolean);if(!all.length)return null;const lastDate=all.map(r=>r.date).sort().at(-1);const ym=lastDate.slice(0,7);let total=0,has=false;for(const c of channels()){const rs=rows(c.id).filter(r=>r.date.slice(0,7)===ym);if(rs.length){total+=rs[0].asset;has=true}}return has?total:null}
function maxDrawdown(rs){let peak=-Infinity,peakDate=null,maxDd=0,maxDdDate=null;for(const r of rs){if(r.asset>peak){peak=r.asset;peakDate=r.date}const dd=r.asset-peak;if(dd<maxDd){maxDd=dd;maxDdDate=r.date}}return{value:maxDd,peakDate,date:maxDdDate}}
function renderSummary(){const t=totalLatest(),p=totalPrev(),ms=monthStartTotal();const diff=change(t,p),mdiff=change(t,ms);document.getElementById("summary").innerHTML=`
<div class="card"><h2>総資産</h2><div class="big">${yen(t)}</div><div class="small">登録済み資産グループ合計</div></div>
<div class="card"><h2>前回比</h2><div class="big ${diff>=0?"good":"bad"}">${diff==null?"-":yen(diff)}</div><div class="small">登録済みデータ同士の比較</div></div>
<div class="card"><h2>月初比</h2><div class="big ${mdiff>=0?"good":"bad"}">${mdiff==null?"-":yen(mdiff)}</div><div class="small">最新月の初回データ比</div></div>
<div class="card"><h2>総評</h2><button class="commentBtn" onclick="openMarketMemo()">💬</button><div class="small">資産間のつながりを見る</div></div>`}
function renderChannelTable(){const total=totalLatest();const trs=channels().map(c=>{const r=latest(c.id),pr=prev(c.id),memo=lastMemoForChannel(c.id);const diff=r&&pr?r.asset-pr.asset:null;const share=total&&r?r.asset/total:null;return`<tr><td><button class="nameBtn" onclick="openChannelDetail('${c.id}')">${c.name}</button></td><td><span class="purpose">${mainPurposeLabel(c)}</span></td><td>${r?yen(r.asset):"未登録"}</td><td class="${diff>=0?"good":"bad"}">${diff==null?"-":yen(diff)}</td><td>${r?yen(r.profit):"-"}</td><td>${share==null?"-":(share*100).toFixed(1)+"%"}</td><td><button class="commentBtn ${memo?"":"empty"}" onclick="openChannelMemo('${c.id}')">${memo?"💬":"○"}</button></td></tr>`}).join("");document.getElementById("channelTable").innerHTML=`<table><thead><tr><th>資産グループ</th><th>目的</th><th>評価額</th><th>前回比</th><th>損益</th><th>比率</th><th>コメント</th></tr></thead><tbody>${trs}</tbody></table>`}
function setupControls(){document.getElementById("channelSelect").innerHTML=channels().map(c=>`<option value="${c.id}">${c.name}</option>`).join("");document.getElementById("channelSelect").value=selectedChannel;document.getElementById("channelSelect").onchange=e=>{selectedChannel=e.target.value;renderChart();renderDataTable()};document.querySelectorAll("[data-range]").forEach(btn=>{btn.classList.toggle("active",btn.dataset.range===selectedRange);btn.onclick=()=>{selectedRange=btn.dataset.range;setupControls();renderChart();renderDataTable()}})}
function renderChart(){window.AssetVisionChart.renderChart({selectedChannel,selectedRange,channel,rows})}
function renderDataTable(){const rsFull=rows(selectedChannel);const rs=rangeRows(rsFull,selectedRange).slice().reverse().slice(0,50);document.getElementById("dataTable").innerHTML=`<table><thead><tr><th>日付</th><th>評価額</th><th>元本/拠出金</th><th>損益</th><th>損益率</th><th>前回比</th></tr></thead><tbody>${rs.map(r=>{const idx=rsFull.findIndex(x=>x.date===r.date);const pr=idx>0?rsFull[idx-1]:null;const diff=pr?r.asset-pr.asset:null;return`<tr><td>${dstr(r.date)}</td><td>${yen(r.asset)}</td><td>${yen(r.principal)}</td><td>${yen(r.profit)}</td><td>${pct(r.profitRate)}</td><td class="${diff>=0?"good":"bad"}">${diff==null?"-":yen(diff)}</td></tr>`}).join("")}</tbody></table>`}
function stars(c){if(c==null)return"-";const n=Math.round(c*5);return"★★★★★".slice(0,n)+"☆☆☆☆☆".slice(0,5-n)}
function openMarketMemo(){const m=latestMarketMemo();if(!m){openModal("今日の総評",`<div class="small">総評コメントはありません。</div>`);return}openModal("今日の総評",`<h3>市況</h3><div>${m.summary}</div><h3>資産間のつながり</h3><div>${m.relation}</div><h3>今日の学び</h3><div>${m.learning}</div><div class="confidence">信頼度：${stars(m.confidence)} / tags: ${(m.tags||[]).join(", ")}</div>`)}
function openChannelMemo(id){const c=channel(id),m=lastMemoForChannel(id);if(!m){openModal(`${c.name} のコメント`,`<div class="small">コメントはまだありません。</div>`);return}openModal(`${c.name} のコメント`,`<h3>今日のコメント</h3><div>${m.comment}</div><h3>今日の学び</h3><div>${m.learning}</div><div class="confidence">信頼度：${stars(m.confidence)}</div>`)}
function openChannelDetail(id){const c=channel(id),rs=rows(id),r=rs.at(-1),pr=rs.at(-2),diff=r&&pr?r.asset-pr.asset:null;const high=rs.length?rs.reduce((a,b)=>b.asset>a.asset?b:a,rs[0]):null;const low=rs.length?rs.reduce((a,b)=>b.asset<a.asset?b:a,rs[0]):null;const dd=rs.length?maxDrawdown(rs):null;openModal(`${c.name} の詳細`,`<div class="detailGrid"><div class="detailItem"><b>目的</b>${allPurposeLabels(c)}</div><div class="detailItem"><b>最新資産</b>${r?yen(r.asset):"未登録"}</div><div class="detailItem"><b>前回比</b><span class="${diff>=0?"good":"bad"}">${diff==null?"-":yen(diff)}</span></div><div class="detailItem"><b>損益</b>${r?yen(r.profit):"-"} / ${r?pct(r.profitRate):"-"}</div><div class="detailItem"><b>最高値</b>${high?yen(high.asset):"-"}<br><span class="small">${high?dstr(high.date):""}</span></div><div class="detailItem"><b>最低値</b>${low?yen(low.asset):"-"}<br><span class="small">${low?dstr(low.date):""}</span></div></div><h3>運用方針</h3><div>${c.policy||"-"}</div><h3>メモ</h3><div>${c.note||"-"}</div><div class="confidence">最大ドローダウン：${dd?yen(dd.value):"-"} ${dd?`(${dstr(dd.peakDate)} → ${dstr(dd.date)})`:""}</div>`)}
function init(){mergeSavedRows();document.getElementById("appVer").textContent=`${DB.app.name} v${DB.app.version}`;renderSummary();renderChannelTable();setupControls();renderChart();renderDataTable();window.AssetVisionImport.setup({rows,openModal,closeModal,closeModalIfOpen,refreshAfterSave:channelId=>{renderSummary();renderChannelTable();selectedChannel=channelId;setupControls();renderChart();renderDataTable()}});document.getElementById("modalBackdrop").addEventListener("click",e=>{if(e.target.id==="modalBackdrop")closeModal()})}
init();
