const DB=window.ASSET_LIFELOG_DB;let selectedChannel="ideco_gold";let selectedRange="1Y";
const {yen,pct,dstr,byDate}=window.AssetVisionCommon;
const {loadSavedRows,persistSavedRows,mergeSavedRows}=window.AssetVisionStorage;
const {openModal,closeModal,closeModalIfOpen}=window.AssetVisionModal;
const channels=()=>DB.channels.filter(c=>c.active).sort((a,b)=>(a.displayOrder??0)-(b.displayOrder??0));const channel=id=>DB.channels.find(c=>c.id===id);
const rows=id=>DB.accountDaily.filter(r=>r.channelId===id&&r.asset!=null).sort(byDate);const purpose=id=>DB.purposeMaster.find(p=>p.id===id);const latest=id=>rows(id).at(-1);const prev=id=>rows(id).at(-2);function allPurposeLabels(c){return(c.purposes||[]).map(id=>{const p=purpose(id);return p?`${p.icon} ${p.label}`:id}).join(" / ")}
function lastMemoForChannel(id){return DB.channelMemos.filter(m=>m.channelId===id).sort(byDate).at(-1)}function latestMarketMemo(){return DB.marketMemos.slice().sort(byDate).at(-1)}
function maxDrawdown(rs){let peak=-Infinity,peakDate=null,maxDd=0,maxDdDate=null;for(const r of rs){if(r.asset>peak){peak=r.asset;peakDate=r.date}const dd=r.asset-peak;if(dd<maxDd){maxDd=dd;maxDdDate=r.date}}return{value:maxDd,peakDate,date:maxDdDate}}
function renderSummary(){window.AssetVisionDashboard.renderSummary({channels,latest,prev,rows})}
function renderChannelTable(){window.AssetVisionDashboard.renderChannelTable({channels,latest,prev,purpose,lastMemoForChannel})}
function setupControls(){document.getElementById("channelSelect").innerHTML=channels().map(c=>`<option value="${c.id}">${c.name}</option>`).join("");document.getElementById("channelSelect").value=selectedChannel;document.getElementById("channelSelect").onchange=e=>{selectedChannel=e.target.value;renderChart();renderDataTable()};document.querySelectorAll("[data-range]").forEach(btn=>{btn.classList.toggle("active",btn.dataset.range===selectedRange);btn.onclick=()=>{selectedRange=btn.dataset.range;setupControls();renderChart();renderDataTable()}})}
function renderChart(){window.AssetVisionChart.renderChart({selectedChannel,selectedRange,channel,rows})}
function renderDataTable(){window.AssetVisionDashboard.renderDataTable({selectedChannel,selectedRange,rows})}
function stars(c){if(c==null)return"-";const n=Math.round(c*5);return"★★★★★".slice(0,n)+"☆☆☆☆☆".slice(0,5-n)}
function openMarketMemo(){const m=latestMarketMemo();if(!m){openModal("今日の総評",`<div class="small">総評コメントはありません。</div>`);return}openModal("今日の総評",`<h3>市況</h3><div>${m.summary}</div><h3>資産間のつながり</h3><div>${m.relation}</div><h3>今日の学び</h3><div>${m.learning}</div><div class="confidence">信頼度：${stars(m.confidence)} / tags: ${(m.tags||[]).join(", ")}</div>`)}
function openChannelMemo(id){const c=channel(id),m=lastMemoForChannel(id);if(!m){openModal(`${c.name} のコメント`,`<div class="small">コメントはまだありません。</div>`);return}openModal(`${c.name} のコメント`,`<h3>今日のコメント</h3><div>${m.comment}</div><h3>今日の学び</h3><div>${m.learning}</div><div class="confidence">信頼度：${stars(m.confidence)}</div>`)}
function openChannelDetail(id){const c=channel(id),rs=rows(id),r=rs.at(-1),pr=rs.at(-2),diff=r&&pr?r.asset-pr.asset:null;const high=rs.length?rs.reduce((a,b)=>b.asset>a.asset?b:a,rs[0]):null;const low=rs.length?rs.reduce((a,b)=>b.asset<a.asset?b:a,rs[0]):null;const dd=rs.length?maxDrawdown(rs):null;openModal(`${c.name} の詳細`,`<div class="detailGrid"><div class="detailItem"><b>目的</b>${allPurposeLabels(c)}</div><div class="detailItem"><b>最新資産</b>${r?yen(r.asset):"未登録"}</div><div class="detailItem"><b>前回比</b><span class="${diff>=0?"good":"bad"}">${diff==null?"-":yen(diff)}</span></div><div class="detailItem"><b>損益</b>${r?yen(r.profit):"-"} / ${r?pct(r.profitRate):"-"}</div><div class="detailItem"><b>最高値</b>${high?yen(high.asset):"-"}<br><span class="small">${high?dstr(high.date):""}</span></div><div class="detailItem"><b>最低値</b>${low?yen(low.asset):"-"}<br><span class="small">${low?dstr(low.date):""}</span></div></div><h3>運用方針</h3><div>${c.policy||"-"}</div><h3>メモ</h3><div>${c.note||"-"}</div><div class="confidence">最大ドローダウン：${dd?yen(dd.value):"-"} ${dd?`(${dstr(dd.peakDate)} → ${dstr(dd.date)})`:""}</div>`)}
function init(){mergeSavedRows();document.getElementById("appVer").textContent=`${DB.app.name} v${DB.app.version}`;renderSummary();renderChannelTable();setupControls();renderChart();renderDataTable();window.AssetVisionImport.setup({rows,openModal,closeModal,closeModalIfOpen,refreshAfterSave:channelId=>{renderSummary();renderChannelTable();selectedChannel=channelId;setupControls();renderChart();renderDataTable()}});document.getElementById("modalBackdrop").addEventListener("click",e=>{if(e.target.id==="modalBackdrop")closeModal()})}
init();
